/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VideoEmbed {
        "autoplay": boolean;
        "playLabel": string;
        "startAt": number;
        "videoId": string;
        "videoProvider": string;
        "videoTitle": string;
        "youtubeParams": string;
    }
}
declare global {
    interface HTMLVideoEmbedElement extends Components.VideoEmbed, HTMLStencilElement {
    }
    var HTMLVideoEmbedElement: {
        prototype: HTMLVideoEmbedElement;
        new (): HTMLVideoEmbedElement;
    };
    interface HTMLElementTagNameMap {
        "video-embed": HTMLVideoEmbedElement;
    }
}
declare namespace LocalJSX {
    interface VideoEmbed {
        "autoplay"?: boolean;
        "playLabel"?: string;
        "startAt"?: number;
        "videoId"?: string;
        "videoProvider"?: string;
        "videoTitle"?: string;
        "youtubeParams"?: string;
    }
    interface IntrinsicElements {
        "video-embed": VideoEmbed;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "video-embed": LocalJSX.VideoEmbed & JSXBase.HTMLAttributes<HTMLVideoEmbedElement>;
        }
    }
}
